### ISSUE TITLE
demo is not working on my Safari, Chrome

### ISSUE THREAD

**Issue by robocop-bob** [anvaka/edgelegend#1]
Hi !,
demo is not working properly on my Safari, Chrome.
Firefox - is working ok.
( it probably 3d pixel.js issue)
Any advice?

**Comment by anvaka** [comment]
Hello,

Are you talking about this demo: https://anvaka.github.io/ngraph.pixel/demo/edit/index.html ?

If so, can you see a spinning cube here: https://get.webgl.org/ ?

**Comment by ghost** [comment]
Yes, it was about discussed demo.
I see, my Safari and Chrome have issue with webgl.

Thx.

**Comment by anvaka** [comment]
Thank you! I should probably provide better error message
